os: linux
language: c
compiler: gcc
env:
  global:
    - MAKEOPTS=-j3
    - GLOBAL_CFLAGS='-O2 -Wall'
    - GLOBAL_CONFIGURE_ARGS='--prefix=/usr'
matrix:
  fast_finish: true
  include:
    - compiler: ": Std Keccak"
      env: myCC='clang' EXTRA_DEPS='pkg-config libssl-dev uthash-dev libjansson-dev libcurl4-openssl-dev libncursesw5-dev' CONFIGURE_ARGS='--enable-keccak --disable-sha256d --enable-cpumining --enable-opencl --disable-other-drivers'
  exclude:
    - compiler: gcc
install:
  - bash .travis.deps
script:
  - bash .travis.script
